#!/bin/bash
while true;
do
status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:19590/ping);

if [[ "$status_code" -eq 500 ]] ; then
  sudo systemctl stop bingo.service;
else
  sleep 5;
fi
done

